# TRON能量租赁系统 - 开发环境Docker Compose配置
# 作者: 系统管理员
# 描述: 开发环境的Docker Compose覆盖配置

version: '3.8'

services:
  # API服务 - 开发模式
  api:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: development
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_NAME: tron_energy_rental_dev
      DEBUG: "true"
      ENABLE_SWAGGER: "true"
      LOG_LEVEL: debug
      START_MODE: dev
    volumes:
      - ../../:/app
      - /app/node_modules
      - app_logs:/app/logs
    ports:
      - "3001:3001"
      - "3000:3000"  # 前端开发服务器
    command: pnpm run dev

  # PostgreSQL - 开发数据库
  postgres:
    environment:
      POSTGRES_DB: tron_energy_rental_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # Redis - 开发缓存
  redis:
    ports:
      - "6379:6379"

  # 禁用生产环境服务
  scheduler:
    profiles:
      - disabled

  telegram-bot:
    profiles:
      - disabled

  nginx:
    profiles:
      - disabled

  prometheus:
    profiles:
      - disabled

  grafana:
    profiles:
      - disabled
